import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Cafekopp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Besøk vår&nbsp;
              <a href="https://www.facebook.com/CafeKoppCatering/"><code className={styles.code}>Facebookside</code></a>
          </p>
          <div>
            <a
              href="https://steffaloff.cloud"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}Steffaloff

            </a>
          </div>
        </div>

        <div className={styles.center}>
            <h1>CAFEkopp</h1>
            <p>catering</p>


        </div>

        <div className={styles.grid}>
            <Link className={styles.card} href="/meny">

            <h2 className={inter.className}>
              Meny <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              God apetitt
            </p>
          </Link>

            <Link className={styles.card} href="/tjenester">
            <h2 className={inter.className}>
              Tjenester <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Hva vi leverer
            </p>
          </Link>

            <Link className={styles.card} href="/omoss">
            <h2 className={inter.className}>
              Om Oss <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Hvem er vi?
            </p>
          </Link>

            <Link className={styles.card} href="/kontakt">
                <h2 className={inter.className}>
                    Kontakt <span>-&gt;</span>
                </h2>
                <p className={inter.className}>
                    Kontakt oss for en hyggelig prat
                </p>
            </Link>
        </div>
      </main>
    </>
  )
}
